"use client";
import { Inter } from "next/font/google";
import Footer from "../components/footer";
import "./globals.scss";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faList } from "@fortawesome/free-solid-svg-icons";
import "../components/styles/header.scss";
import React, { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Davy Crow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isOpen, setIsOpen] = useState(false);

  // fonction qui permet de changer le statut du top
  const ShowContent = () => {
    setIsOpen(!isOpen);
  };

  // Permet d'appeler dynamiquement la classe hidden ou non pour afficher la navigation
  const showtext = isOpen ? "header-list--visible" : "header-list";
  const showMain = isOpen ? "main-bloc--transform" : "main-bloc"; 

  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div className="page-container">
          <div>
            <div className="header">
              <div className="header-title">
                <h1>Davy Crow</h1>
                <button onClick={ShowContent} className="header-title__list">
                  <FontAwesomeIcon icon={faList} className="logo" />
                </button>
              </div>
              <nav className={showtext}>
                {/* on ferme la fenêtre "sommaire"/Header avec ShowContent dès qu'on clique sur un lien */}
                <Link href="/" onClick={ShowContent}>
                  Nouveautés
                </Link>
                <Link href={"/product/" + "OO"} onClick={ShowContent}>
                  Oeuvres originales
                </Link>
                <Link href={"/product/" + "SE"} onClick={ShowContent}>
                  Sérigraphies
                </Link>
                <Link href="/about" onClick={ShowContent}>
                  A propos
                </Link>
                <Link href="/contact" onClick={ShowContent}>
                  Contact
                </Link>
              </nav>
            </div>
          </div>
          <div className={showMain}>
          {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
